Change Version Info in Tizen Studio setup
Samsung/tizen-docs pull request #1292
Opened 2020-10-19 04:54 UTC by mijin85cho

Signed-off-by: Mijin, Cho <mijin85.cho@samsung.com>

### Change Description ###

According to "OS and System Requirements"
the at least supported version for Ubuntu is 16.04.
So I remove the 14.04 description in "Driver".

### Bugs Fixed ###

- https://github.com/Samsung/tizen-docs/issues/1291

2020-10-19 04:54 UTC, mijin85cho commented
@annie-samsung Would you please check the content update and the accuracy?

2020-10-19 05:43 UTC, manishtr commented
The change looks fine , thanks

2020-10-19 05:47 UTC, annie-samsung commented
> @annie-samsung Would you please check the content update and the accuracy?

@mijin85cho I am going to ask Nawab to check this as he is been updating these pages as part of content revamp.

2020-10-19 06:03 UTC, nawab-samsung requested changes
@mijin85cho request you to kindly verify the comment, thanks

2020-10-19 06:33 UTC, mijin85cho commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
- On Ubuntu ...
   As this table cell is in column for "Ubuntu" (also as you can see in above line), I think we can skip it.
- ... and 18.04
   Would you please get the confirmation that the Ubuntu 18.04 requires Intel driver version 8.0.1 and higher?
   I think for this we need someone other, for example @manishtr's confirmation for the accuracy.

2020-10-19 10:27 UTC, nawab-samsung commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
@mijin85cho  sure, you are right. For drivers we need confirmation.

2020-10-19 10:29 UTC, nawab-samsung commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
@manishtr Is this true for 18.04?  the Intel driver version must be 8.0.1 or higher.

2020-10-19 10:29 UTC, manishtr commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
16.04 and 18.04 are the main versions supported, so only mentioning them is fine

2020-10-20 04:51 UTC, nawab-samsung commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
@manishtr please correct me if I am wrong 

 <p>In 16.04 and 18.04, the Intel driver version must be 8.0.1 or higher.</p>

2020-10-20 07:09 UTC, manishtr commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
yes its correct

2020-10-20 07:09 UTC, manishtr approved these changes

2020-10-20 07:59 UTC, mijin85cho commented on docs/application/tizen-studio/setup/prerequisites.md
> +<p>In 16.04, the Intel driver version must be 8.0.1 or higher.</p>
> In 16.04 and 18.04, the Intel driver version must be 8.0.1 or higher.
The suggestion is applied.

2020-10-20 09:49 UTC, nawab-samsung approved these changes
Thanks @manishtr & @mijin85cho

2020-10-20 10:19 UTC, merged