[NUI] update nui-widget-app guide
Samsung/tizen-docs pull request #1379
Opened 2020-12-21 06:45 UTC by tscholb

add case for "Destroy a NUI Widget View"

### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

2020-12-23 06:35 UTC, nawab-samsung requested changes
@tscholb Request you to kindly incorporate the comments.

2020-12-23 06:35 UTC, nawab-samsung commented on docs/application/dotnet/guides/applications/nui-widget-app.md
>  ## Related Information
```suggestion
## Related information

2020-12-23 06:35 UTC, nawab-samsung commented on docs/application/dotnet/guides/applications/nui-widget-app.md
> +For terminate the widget view, All resources for widget must be released.
```suggestion
To terminate the widget view, use `TerminateWidget()`, and also ensure to release all the resources used by the widget view:

2020-12-28 04:01 UTC, nawab-samsung commented
@tscholb  Request you to kindly incorporate the comments.

2021-01-04 09:14 UTC, nawab-samsung commented
@tscholb Gentle Reminder: 
Request you to kindly incorporate the comments.

2021-01-06 08:36 UTC, nawab-samsung commented
@tscholb Gentle Reminder:
Request you to kindly incorporate the comments.

2021-01-12 06:05 UTC, nawab-samsung commented
@tscholb Gentle Reminder:
Request you to kindly incorporate the comments.

2021-01-18 04:33 UTC, nawab-samsung commented
@tscholb Gentle Reminder:
Request you to kindly incorporate the comments.

2021-01-18 04:41 UTC, closed without merging

2021-01-18 04:43 UTC, tscholb commented
I'm sorry but this PR need to delete.
I will upload it again after revision.