Add guide for stability-monitor
Samsung/tizen-docs pull request #1429
Opened 2021-04-16 11:52 UTC by mmoscicki2

### Change Description ###

Added porting guide for stability-monitor.

Continuation of https://github.com/Samsung/tizen-docs/pull/1417

2021-04-21 07:32 UTC, nawab-samsung requested changes
@mmoscicki2 Giving the last set of comments, just to ensure consistency within the page. Please incorporate the comments. 
Thanks.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +Resources are consumed by various processes and are classified according to their type: application or service. Applications have the type as native, web app and .NET, with the state as foreground an
```suggestion
Resources are consumed by various processes and are classified according to their type: application or service. Applications have the type as native, web app, and .NET, with the state as foreground and background. The process parameters are distinguished in configuration and various parameters can be assigned to different services and applications. When excessive use of resources abnormality is detected, an appropriate D-Bus signal is sent, and an optional abnormality report is generated.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +The stability monitor relies on the kernel module, which collects information about processes state in the system in most resource efficient way. This raw data is exposed via `/proc/tsm` interface.
```suggestion
The stability monitor relies on the kernel module, which collects information about processes state in the system in the most resource-efficient way. This raw data is exposed using the `/proc/tsm` interface.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +The purpose of stability-monitor service is to:
```suggestion
The purpose of stability monitor service is to:

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +     Specifies the maximum I/O usage in megabytes per second (MB/s). The I/O usage is unlike the usage of CPU and memory values.
```suggestion
     Specifies the maximum I/O usage in Megabytes per second (MB/s). The I/O usage is unlike the usage of CPU and memory values.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +     Specifies the maximum allowed memory usage. A value of `1.0` means that the process can use all available memory. It is system-wide parameter, and there is no way to specify it in megabytes.
```suggestion
     Specifies the maximum allowed memory usage. A value of `1.0` means that the process can use all available memory. It is the system-wide parameter, and there is no way to specify it in Megabytes.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +     Specifies the sampling rate (Hz). This is the process data update frequency. Maximum allowed value is specified by **sampling_rate** from the `global` section.
Shouldn't **sampling_rate** be in code styling instead? If no, ignore the comment.

2021-04-21 07:32 UTC, nawab-samsung commented on docs/platform/porting/system.md
> +When the abnormality is detected, the stability monitor sends one of the following D-Bus signals, depending on the module or parameter that detected or caused the abnormality:
```suggestion
When the abnormality is detected, the stability monitor sends one of the following D-Bus signals, depending on the module or parameter that detects or causes the abnormality:

2021-04-23 04:54 UTC, nawab-samsung approved these changes
@mmoscicki2 Thanks for incorporating the comments.

2021-04-23 07:31 UTC, mmoscicki2 commented
@nawab-samsung Thank you for review

2021-04-23 12:03 UTC, merged