Fix wrong profile information for TV Maps app
Samsung/tizen-docs pull request #1473
Opened 2021-06-10 01:50 UTC by sgchoi5

(M) => (T)

2021-06-10 09:01 UTC, nawab-samsung approved these changes
@sgchoi5 Thanks.

2021-06-11 04:24 UTC, sgchoi5 commented
Fixed more wrong path: https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/WeatherWatch
https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/**Xamarin.Forms**/WeatherWatch

2021-06-11 05:06 UTC, nawab-samsung requested changes
@sgchoi5 How about this suggestion to give the path to readme file?

2021-06-11 05:06 UTC, nawab-samsung commented on docs/application/dotnet/samples/watch/overview.md
> +			You can get detailed information from <a href="https://github.com/Samsung/Tizen-CSharp-Samples/blob/master/Wearable/Xamarin.Forms/WeatherWatch" target="_blank"><strong>readme file</strong> of Weat
```suggestion 
                        You can get detailed information from <a href="https://github.com/Samsung/Tizen-CSharp-Samples/blob/master/Wearable/Xamarin.Forms/WeatherWatch/README.md" target="_blank"><strong>the readme file</strong></a> of WeatherWatch.</p>

2021-06-11 05:17 UTC, sgchoi5 commented on docs/application/dotnet/samples/watch/overview.md
> +			You can get detailed information from <a href="https://github.com/Samsung/Tizen-CSharp-Samples/blob/master/Wearable/Xamarin.Forms/WeatherWatch" target="_blank"><strong>readme file</strong> of Weat
Updated!

2021-06-11 05:48 UTC, nawab-samsung approved these changes
@sgchoi5 thanks a lot for applying my suggestion.

2021-06-11 06:36 UTC, merged