Add additional comments for better description of battery property
Samsung/tizen-docs pull request #1490
Opened 2021-07-30 01:15 UTC by sgchoi5

Added some description using remarks TAG.

2021-07-30 01:15 UTC, sgchoi5 reviewed
LGTM

2021-08-02 05:43 UTC, sagarkedari requested changes
@sgchoi5 I have reviewed the PR and added my feedback comments. Kindly check and update.

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/wearable/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/wearable/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/mobile/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/mobile/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/iot-headless/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/iot-headless/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/iot-headed/6.0/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:14 UTC, sgchoi5 commented on docs/application/native/api/iot-headed/5.5/group__CAPI__SYSTEM__DEVICE__BATTERY__MODULE.html
> +<dl class="remark"><dt><b>Remarks:</b></dt><dd>If fuel gauge hardware does not provide average current or average voltage, CURRENT_AVERAGE/VOLTAGE_AVERAGE can be substituted by CURRENT_NOW/VOLTAGE_NO
Thanks!, fixed it

2021-08-03 01:19 UTC, sgchoi5 reviewed
Fixed all issues.

2021-08-03 05:14 UTC, sagarkedari approved these changes
@sgchoi5 Thank you for updating the feedback comments. The changes looks fine now.

2021-08-03 18:38 UTC, merged