[web index][4.0-5.5] Fixed index file to include Libteec module
Samsung/tizen-docs pull request #1498
Opened 2021-08-11 07:56 UTC by pkosko

Libteec module was supported on TV since 4.0, but it was not present in
index file.

Reference - 4.0 ACR https://code.sec.samsung.net/jira/browse/TWDAPI-172

2021-08-11 08:44 UTC, dmichaluk approved these changes

2021-08-18 06:21 UTC, sagarkedari requested changes
@pkosko, I have reviewed the files and included my feedback commments. Kindly check and update the comments.

2021-08-23 07:08 UTC, pkosko commented
@sagarkedari thank you for all your comments. However, this PR is only copying a html file of existing API from other profiles. Additionally, please notice that libteec API is deprecated since Tizen 6.5 - because of that I think that any changes in libteec.html file are not needed.

@mijin85cho I've tried to fix the problem with table of context https://github.com/Samsung/tizen-docs/pull/1498#discussion_r690068427 with adding entries to toc.xml file - unfortunately, the result on https://docs1.stg.tizen.org/application/web/api/4.0/device_api/tv/index.html is unchanged. Could you please guide me how to add entry to TOC?

2021-08-23 09:44 UTC, mijin85cho commented
> @mijin85cho I've tried to fix the problem with table of context [#1498 (comment)](https://github.com/Samsung/tizen-docs/pull/1498#discussion_r690068427) with adding entries to toc.xml file - unfortunately, the result on https://docs1.stg.tizen.org/application/web/api/4.0/device_api/tv/index.html is unchanged. Could you please guide me how to add entry to TOC?

docs1.stg.tizen.org is to check master branch. For the PR 1498, you should use below (Please check 1498 in the URL)

https://docs1.stg.tizen.org/staging/1498/application/web/api/4.0/device_api/tv/index.html

Also there is a bug that if you click the LNB in Web api pages, the page jumps to docs1.stg.tizen.org, not docs1.stg.tizen.org/staging/1498/... It it giving confusion to your checking, in my thought.

2021-08-23 10:23 UTC, pkosko commented
@mijin85cho thank you for pointing me an issue with links, I didn't notice that after clicking a link I jumped out from staging for my PR.
On your link https://docs1.stg.tizen.org/staging/1498/application/web/api/4.0/device_api/tv/index.html TOC looks good:
![image](https://user-images.githubusercontent.com/38070006/130431884-85e2a5be-1f35-4fda-bd79-26e89999d2c4.png)

@sagarkedari @mijin85cho Is it acceptable to you to leave all other comments unchanged as the libteec API is deprecated since 6.5?

2021-08-24 07:42 UTC, mijin85cho commented
> @sagarkedari @mijin85cho Is it acceptable to you to leave all other comments unchanged as the libteec API is deprecated since 6.5?

In case of the comments on device_api/tv/index.html, I think they deserve consideration to apply. What do you think?

>I am not sure if "LibTeec API" inside the parenthesis is required in the sentence? Please check.
>
>Also, kindly check if "Trust Zone" is supposed to be written as "TrustZone" (i.e. without space between words)?

2021-08-30 07:34 UTC, annie-samsung commented
Meging this PR, @sagarkedari as discussed keep an eye if the API reference appear correctly under the versions mentioned.

2021-08-30 07:34 UTC, merged