WIP: widget application
Samsung/tizen-docs pull request #1501
Opened 2021-08-17 14:36 UTC by mihashco

2021-11-04 07:45 UTC, sagarkedari requested changes
@mihashco , I have reviewed and added my feedback comments. Kindly check and incorporate the changes.

2021-11-16 14:35 UTC, mihashco commented on docs/application/dotnet/guides/applications/uiapplication/widget-app.md
> +An instance of the widget is managed by a [Widget Viewer](./) application. Widget process is created when a widget application is added to the widget viewer.
This file is introduced in #1505

2021-11-24 07:25 UTC, mihashco commented on docs/application/dotnet/guides/applications/uiapplication/widget-app.md
> +</div>
I'm not sure how to do that. Markdown file don't create those spaces.

2021-11-30 05:55 UTC, sagarkedari requested changes
@mihashco , I have only following comment to be addressed yet. Please check and incorporate the changes.

2021-11-30 05:55 UTC, sagarkedari commented on docs/application/dotnet/guides/applications/uiapplication/widget-app.md
> +# Widget application
I still issue with heading format in this topic. Following headings are still in title case. Please change to sentence case.

- Widget Instance States and Events
- Data Sharing Between the widget application and other applications

2021-11-30 12:42 UTC, sagarkedari approved these changes
@annie-samsung, This PR is approved from my end.

2021-12-01 10:29 UTC, merged