[6.5][NET] Changed widget-control to widget-management.
Samsung/tizen-docs pull request #1507
Opened 2021-08-20 14:27 UTC by mihashco

Changes:
- Title was changed because widget-control suggest something that controll
widget, but widget-control is responsible for widget applications
managent like viewing installed widgets list, removing widget etc.
- Some code snippets was fixed.

2021-09-02 14:37 UTC, sagarkedari requested changes
@mihashco , I have reviewed the files and added my feedback comments. Kindly check and incorporate the changes.

2021-09-17 12:56 UTC, sagarkedari approved these changes
@annie-samsung, The PR is approved from my end.

2021-09-24 10:31 UTC, annie-samsung commented
@mihashco, @sagarkedari is this specific to 6.5 release? Why is this PR raised to 6.5 branch

2021-10-01 05:41 UTC, sagarkedari requested changes
@mihashco, Please update as per comment provided.

2021-10-01 05:41 UTC, sagarkedari commented on docs/application/dotnet/guides/app-management/widget-management.md
> +# Widget Management
@mihashco, Per below comment, please change the base branch from "Tizen 6.5" to "master" for this PR.
https://github.com/Samsung/tizen-docs/pull/1507#issuecomment-926521854

@annie-samsung, You are correct, this PR should have been raised on master branch. Thank you for pointing this out.

2021-11-02 11:30 UTC, merged

2021-11-03 01:47 UTC, mijin85cho commented
Thanks for reviewing & merging this PR @annie-samsung 
However, as Tizen 6.5 is published last week, the updates to tizen_6.5_prepare will not be applied to master.
(tizen_6.5_prepare is merged to master last week.)

So for the PR to tizen_6.5_prepare, 
please guide authors to change the target branch to master, or create a new PR that works on master branch.

2021-11-03 08:30 UTC, annie-samsung commented
@mihashco, could you please raise this PR to master branch, could you do that for all your PRs?

2021-11-03 08:46 UTC, annie-samsung commented
> Thanks for reviewing & merging this PR @annie-samsung However, as Tizen 6.5 is published last week, the updates to tizen_6.5_prepare will not be applied to master. (tizen_6.5_prepare is merged to master last week.)
> 
> So for the PR to tizen_6.5_prepare, please guide authors to change the target branch to master, or create a new PR that works on master branch.

@mijin85cho, I had mentioned this in chat, to Michal,  I was in two minds should I close or merge this PR post approving.