[6.5][NET] Move NUI and WCircularUI to User interface section.
Samsung/tizen-docs pull request #1511
Opened 2021-09-09 10:04 UTC by mihashco

This commit moves NUI and WCircularUI to one user interface section.
User interface is common and important topic. This change makes it
easier to search for it in the documentation tree.

Modified files: 
docs/applicaiton/toc_all.md
docs/application/dotnet/guides/index.md

2021-09-14 06:45 UTC, annie-samsung commented
@sagarkedari this is 1491 PR content re-raised, could you check that all our points discussed in 1491 is addressed.

2021-09-16 13:05 UTC, sagarkedari requested changes
@mihashco, I have added my review feedback comments. Kindly check and incorporate the changes.

2021-09-17 08:32 UTC, mihashco commented on docs/application/toc_all.md
> +### User interface
@annie-samsung If you want I can move Display Web Content to guides in separated PR. Please let me know to confirm that change.

2021-09-17 08:36 UTC, mihashco commented on docs/application/dotnet/guides/index.md
> +                <p class="h3 card-title">User interface</p>
Not all of them. Display Web Content is at the end of the list.

2021-09-21 05:11 UTC, sagarkedari commented on docs/application/dotnet/guides/index.md
> +                <p class="h3 card-title">User interface</p>
@mihashco, Yes. After @annie-samsung confirmation on raising new PR for relocating "display web content" in the TOC file,  I thought of making change in this topic/file as well and include both files in the new PR.

2021-09-28 09:22 UTC, sagarkedari requested changes
@mihashco, I have added my review feedback comments. Kindly check and incorporate the changes.

2021-09-30 05:59 UTC, mihashco commented on docs/application/dotnet/guides/index.md
> +                <p class="h3 card-title">User interface</p>
This commit don't change gaps. It only adds one box. Looks of the index page was introduced in other commit.

2021-10-01 05:18 UTC, sagarkedari approved these changes
@annie-samsung, This PR is approved from my end. Regarding following two comments, I have made a note to check with concerned developer for these issue resolution.

https://github.com/Samsung/tizen-docs/pull/1511#discussion_r717259627
https://github.com/Samsung/tizen-docs/pull/1511#discussion_r717301696

2021-10-01 08:54 UTC, annie-samsung commented
Merging this PR as it is long pending and reviewed by Sagar twice now

2021-10-01 08:55 UTC, merged