[NUI][Hotreloading] Hotreloading guide
Samsung/tizen-docs pull request #1519
Opened 2021-09-30 00:25 UTC by patrykka

### Change Description ###

Describe your changes here.

For instance,
 - Fix broken links of native application docs.
 -  ...

### Bugs Fixed ###

Provide links to bugs here

For instance,

 - Issue #265

### API Changes ###

In case of ACR, put the link of ACR

For instance,

 - ACR: ACR-1120

2021-10-04 06:24 UTC, sagarkedari requested changes
@patrykka, I have reviewed and included my feedback comments. Kindly check and incorporate the changes.

2021-10-04 06:24 UTC, sagarkedari commented on docs/application/dotnet/guides/hot-realoading/beholder.md
> +![extension setup](docs/extension_setup.png)
Global comment:

We add figures after end of steps/descriptions in the guides. Could you please follow the same and move figures at the end of steps/descriptions?

2021-10-04 06:24 UTC, sagarkedari commented on docs/application/dotnet/guides/hot-realoading/beholder.md
> +1. On the menu bar, choose **Extensions > Manage Extensions**.
```suggestion
1. On the menu bar, select **Extensions > Manage Extensions**.
```

2021-10-04 06:24 UTC, sagarkedari commented on docs/application/dotnet/guides/hot-realoading/beholder.md
> +If even in the screen that looks only go through several stages, without a step back, you can update the screen is changed files are applied
I am not clear on what we are trying to say in this paragraph. Could you please check and rephrase this correctly?

2021-10-15 09:01 UTC, mijin85cho commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +![Beholder_Menu](./media/menu.png)
It seems the image is captured after above process. (The menu shows Disable Beholder.)
How about using an image captured during the process?

2021-10-21 12:47 UTC, annie-samsung commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +### Note
If this is Note then suggest to follow the correct style

2021-11-11 08:17 UTC, sagarkedari requested changes
@patrykka, I have added my review feedback comments. Kindly check and incorporate the changes.

2021-11-18 06:22 UTC, sagarkedari reviewed
@patrykka , Following are my additional comments from review. Kindly incorporate the changes requested.

2021-11-22 11:30 UTC, patrykka commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +# Hot reloading
Base branch changed

2021-11-29 13:39 UTC, sagarkedari approved these changes
@annie-samsung , This PR is approved from my end.

2021-12-02 06:09 UTC, annie-samsung reviewed
@patrykka, could you check the below comments and address them?

2021-12-02 06:09 UTC, annie-samsung commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +Hot reloading feature allows you to inject new edited files without stopping the running app. In this way, you do not lose state of the app that is especially useful when editing the UI.
```suggestion
Hot reloading feature allows you to inject newly edited files at runtime without stopping the app. This way, you do not lose the state of the app that is especially useful when editing the UI.
```

2021-12-02 06:09 UTC, annie-samsung commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +The following video demonstrates hot reloading an app running on Tizen TV emulator.
```suggestion
The following video demonstrates hot reloading an app at runtime on Tizen TV emulator:
```

2021-12-02 06:09 UTC, annie-samsung commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +
It would be good if a lead line could be added.

2021-12-02 06:09 UTC, annie-samsung commented on docs/application/dotnet/guides/hot-reloading/overview.md
> +
It would be good if a lead line could be added.

2021-12-07 06:16 UTC, annie-samsung approved these changes
Approving

2021-12-07 06:16 UTC, merged