Add new documents for Tizen Image Creator
Samsung/tizen-docs pull request #1538
Opened 2021-10-20 10:28 UTC by jay4peace

### Change Description ###

- Add new documents for Tizen Image Creator (TIC)
- TIC is new tool to create Tizen binary image

2021-11-03 12:05 UTC, sagarkedari requested changes
@jay4peace, I have reviewed the files and added my feedback comments. Kindly check and incorporate the changes.

2021-11-04 06:55 UTC, jay4peace commented on docs/platform/developing/creating-tic.md
> +## How to use TIC
This section is for setting up TIC on user's PC, so I think, `Set up TIC on your PC` is better than `Create a Tizen image using TIC`

2021-11-04 07:35 UTC, jay4peace commented on docs/platform/developing/creating-tic.md
> +- Open any browser with <http://127.0.0.1:8088>
`http://127.0.0.1:8088` is the address for the TIC service on local host PC

2021-11-08 05:20 UTC, sagarkedari requested changes
@jay4peace , I have reviewed and provided my additional feedback comments. Kindly check and incorporate the changes.

2021-11-11 13:31 UTC, sagarkedari requested changes
@jay4peace, Please incorporate the requested changes.

2021-11-17 13:48 UTC, sagarkedari approved these changes
@annie-samsung , This PR is approved from my end.

2021-11-19 06:30 UTC, jay4peace commented
@annie-samsung , @journey2w Is there anything I have to do to proceed?

2021-11-23 05:44 UTC, jay4peace commented
@mijin85cho @annie-samsung @journey2w Please move on to next step

2021-11-23 08:15 UTC, mijin85cho commented
@annie-samsung Would you please check this PR? If there is no more issue, how about merging it?

2021-11-23 08:53 UTC, merged